version: "3.9"
services:
    web:
        image: python:3.8.8
        build: .
        volumes:
          - '.:/base_directory'
        ports:
          - "8000:8000"
        volumes:
            - type: bind
              source: ./
              target: /code
        working_dir: /code
        command: bash -c "pipenv install && python3 mediquick/manage.py runserver 0.0.0.0:8000"
        depends_on:
          - redis
    redis:
        image: "redis:5"
   


# pipenv lock --clear &&  pipenv install --skip-lock && pipenv graph && ls && pip install channels && pip install -U asgiref &&